addons:
  ssh_known_hosts: schedar.uberspace.de

before_deploy:
  - openssl aes-256-cbc -K $encrypted_238cb97d7468_key -iv $encrypted_238cb97d7468_iv -in deploy_rsa.enc -out ./tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master