version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-php-backend
    ports:
      - '8080:80'
      # - '8443:443'
    volumes:
      - './app/:/app/'
      - './:/docker'
    cap_add:
      - SYS_PTRACE
    privileged: true
    env_file:
      - etc/environment.yml
    environment:
      - VIRTUAL_HOST=.app.docker
      - VIRTUAL_PORT=80
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: blog-db
    volumes: 
      - blogdb:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=letmein
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: blog-phpMyAdmin
    ports: 
      - 8090:80
    depends_on: 
      - db
volumes: 
  blogdb:


