version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ./app/:/app/
      - './:/docker'
    cap_add:
      - SYS_PTRACE
    privileged: true
    env_file:
      - etc/environment.yml
    environment:
      - VIRTUAL_HOST=.app.docker
      - VIRTUAL_PORT=80
